import type { Metadata } from "next";
import { Mona_Sans } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const MonaSans = Mona_Sans({
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Aksantara Muda 2026",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${MonaSans.className} h-full antialiased bg-neutral-100 text-neutral-800`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar />
        {children}
      </body>
    </html>
  );
}
